name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.17]
        java: [zulu@1.8, zulu@1.11, zulu@1.17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - name: Run scripted tests
        run: sbt ++${{ matrix.scala }} scripted